In [86]:
import numpy as np
import pandas as pd

In [87]:
df=pd.read_csv('http://bit.ly/w-data')
print(df.shape)

(25, 2)


In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 528.0 bytes


In [89]:
df.describe()

Hours     Scores
count  25.000000  25.000000
mean    5.012000  51.480000
std     2.525094  25.286887
min     1.100000  17.000000
25%     2.700000  30.000000
50%     4.800000  47.000000
75%     7.400000  75.000000
max     9.200000  95.000000

In [90]:
df.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [91]:
X=df['Hours'].values
Y=df['Scores'].values

In [92]:
X

array([2.5, 5.1, 3.2, 8.5, 3.5, 1.5, 9.2, 5.5, 8.3, 2.7, 7.7, 5.9, 4.5,
       3.3, 1.1, 8.9, 2.5, 1.9, 6.1, 7.4, 2.7, 4.8, 3.8, 6.9, 7.8])

In [93]:
Y

array([21, 47, 27, 75, 30, 20, 88, 60, 81, 25, 85, 62, 41, 42, 17, 95, 30,
       24, 67, 69, 30, 54, 35, 76, 86])

In [94]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                            test_size=0.2, random_state=0)

In [95]:
mean_of_x=np.mean(X_train)
mean_of_y=np.mean(y_train)

In [96]:
mean_of_x

5.24

In [97]:
mean_of_y

53.95

In [98]:
n = len(X_train)
n

20

In [99]:
a=0
b=0
for i in range(n):
  a+=(X_train[i]-mean_of_x)*(y_train[i]-mean_of_y)
  b+=(X_train[i]-mean_of_x)**2
slope_of_line=a/b
slope_of_line

9.910656480642235

In [100]:
c=mean_of_y-(slope_of_line*mean_of_x)
print(slope_of_line,c)

9.910656480642235 2.0181600414346903


In [101]:
maxx=np.max(X_train)+1
minx=np.min(X_train)-1

In [102]:
x=np.linspace(minx,maxx,10)
x

array([ 0.1       ,  1.22222222,  2.34444444,  3.46666667,  4.58888889,
        5.71111111,  6.83333333,  7.95555556,  9.07777778, 10.2       ])

In [103]:
y=c+slope_of_line*x
y

array([  3.00922569,  14.13118463,  25.25314357,  36.37510251,
        47.49706145,  58.61902039,  69.74097933,  80.86293827,
        91.9848972 , 103.10685614])

In [104]:
print(X_test) 
y_pred = c+(slope_of_line*X_test)

[1.5 3.2 7.4 2.5 5.9]


In [105]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})  
df

Actual  Predicted
0      20  16.884145
1      27  33.732261
2      69  75.357018
3      30  26.794801
4      62  60.491033

In [106]:
y_test

array([20, 27, 69, 30, 62])

In [107]:
mean_of_y=np.mean(y_test)

In [108]:
sst=0
ssr=0
n=len(y_test)
for i in range(n):
  sst+=(y_pred[i]-mean_of_y)**2
  ssr+=(y_test[i]-mean_of_y)**2
r2=sst/ssr
print(r2)

1.2055199541753725


In [109]:
x1=9.25
y_ans=c+(slope_of_line*9.25)
print("No of Hours = {}".format(x1))
print("Predicted Score = {}".format(y_ans))

No of Hours = 9.25
Predicted Score = 93.69173248737536
